messages:
  knead_player: "§3你揉了揉 %s，好感度 +1。"
  knead_by_player: "§6你被 %s 揉了揉，好感度 +1。"
  countdown: "§d你刚刚已经揉过别人了，请等待 %s 秒再来～"
  not_enough_args: "§c参数不够！"
  invalid_args: "§c参数错误！"
  scoreboard_switch_to_master: "§3你的记分板已切换至 面点大师榜。"
  scoreboard_switch_to_popular: "§6你的记分板已切换至 最受欢迎榜。"
  scoreboard_master: "§3面点大师榜"
  scoreboard_popular: "§6最受欢迎榜"
